title = "JS访问统计后台配置文件"

debug = true

[server]
port = 9999
max_page_size = 300

[server.cors]
allowed_origins = ["*"]
allowed_headers = ["*"]

[database]
type = "postgres"

[database.dsn]
addr = "47.102.113.82:5432"
db = "postgres"
username = "postgres"
password = "123456"
connect_timeout = 5
max_idle_conns = 30
max_open_conns = 60

[minio]
addr = "47.102.113.82:9000"
access_key_id = "minioadmin"
secret_access_key = "minioadmin"
ssl = false