basePath: /
definitions:
  vo.DataPagination:
    properties:
      data:
        description: 数据
      pagination:
        $ref: '#/definitions/vo.Pagination'
        description: 分页信息
    type: object
  vo.Error:
    properties:
      args:
        items:
          type: string
        type: array
      code:
        type: integer
      msg:
        type: string
    type: object
  vo.InvestDetail:
    properties:
      comment:
        description: 备注
        type: string
      total:
        description: 资金类别 总投资
        type: number
      value:
        description: 投资数额
        type: number
      year:
        description: 年份
        type: string
    type: object
  vo.InvestmentDetail:
    properties:
      detail:
        description: 投资情况数额细节
        items:
          $ref: '#/definitions/vo.InvestDetail'
        type: array
      total:
        description: 总投资
        type: number
      type:
        description: 投资类型
        type: integer
    type: object
  vo.ListReserveProResp:
    properties:
      construct_subject:
        type: string
      create_at:
        type: string
      id:
        type: integer
      level:
        type: integer
      name:
        type: string
      project_type:
        type: integer
      status:
        type: integer
    type: object
  vo.LoginReq:
    properties:
      password:
        description: 密码
        type: string
      user_name:
        description: 用户名
        type: string
    type: object
  vo.LoginResponse:
    properties:
      access_token:
        description: token
        type: string
      expiry:
        description: token 到期时间 默认两小时
        type: integer
      token_type:
        description: 认证类型
        type: string
    type: object
  vo.Pagination:
    properties:
      page:
        description: 请求页
        type: integer
      page_size:
        description: 页大小
        type: integer
      total_count:
        description: 数据总条数
        type: integer
    type: object
  vo.ReserveFilterParam:
    properties:
      construct_subject:
        description: 建设主体
        type: string
      level:
        description: 项目级别
        type: integer
      name:
        description: |-
          以下所有参数，有就传，无则不传
          项目名称
        type: string
      plan_begin:
        description: 计划开始时间
        type: string
      plan_end:
        description: 计划结束时间
        type: string
      project_type:
        description: 项目类型
        type: integer
      status:
        description: 状态
        type: integer
    type: object
  vo.ReserveReq:
    properties:
      add:
        description: 新增建设用地
        type: number
      company_business:
        description: 企/事业单位(家)
        type: integer
      construct_basis_necessity:
        description: 建设依据及必要性
        type: string
      construct_content_scope:
        description: 建设内容及规模
        type: string
      construct_site:
        description: 建设地点
        type: string
      construct_subject:
        description: 建设主体
        type: string
      contract:
        description: 前期工作联系人
        type: string
      enter_db_type:
        description: 入库类别 0:A类,1:B类;2:C类
        type: integer
      implement_type:
        description: 实施类型 0:新开工,1:续建
        type: integer
      investment_detail:
        description: |-
          资金详情 eg:
          "[{\\"type\\":0, \\"total\\":100, \\"detail\\":[{\\"total\\": 100,\\"year\\": \\"2022\\",\\"value\\":20,\\"comment\\":\\"xxx\\"}, {\\"total\\": 100,\\"year\\": \\"2023\\",\\"value\\":30,\\"comment\\":\\"xxx\\"}, ...]}, {}...]"
          type说明： 0:区财政;1:自筹;2:其他
        type: string
      is_land_use:
        description: 是否有用地情况
        type: boolean
      level:
        description: 项目级别 0:区级,1:街镇级
        type: integer
      move_land_comsumption:
        description: 征迁/土地费用
        type: number
      name:
        description: 项目名称
        type: string
      need_collect:
        description: 需征地面积
        type: number
      need_people_move:
        description: 需拆迁农户/居民数(人)
        type: integer
      no_conform_use_plan:
        description: 不符合土地利用规划面积
        type: number
      period:
        description: 建设周期
        type: integer
      phone:
        description: 联系人手机号
        type: string
      plan_begin:
        description: 计划开工时间
        type: string
      point_type:
        description: 重点类型; 0:省重点实施项目,1:省重点预备项目,2:省重大产业项目;3:省4+1项目;4:省6千亿项目;5:市重点实施项目;6:市重点预备项目;7:无重点类型
        type: integer
      project_consumption:
        description: 工程费用
        type: number
      project_type:
        description: 项目类型; 0:安置房,1:道路交通,2:市政设施;3:提升整治;4:卫生;5:五水共治;6:学校;7:其他
        type: integer
      site_photo:
        description: 无拆迁照片
        type: string
      site_red:
        description: 选址红线 0:有拆迁,1:无拆迁
        type: integer
      total:
        description: 总用亩
        type: number
      total_investment:
        description: 总投资
        type: number
      upload_cad_id:
        description: CAD文件ID(上传文件接口返回的ID)
        type: string
    type: object
  vo.ReserveResp:
    properties:
      add:
        description: 新增建设用地
        type: number
      company_business:
        description: 企/事业单位(家)
        type: integer
      construct_basis_necessity:
        description: 建设依据及必要性
        type: string
      construct_content_scope:
        description: 建设内容及规模
        type: string
      construct_site:
        description: 建设地点
        type: string
      construct_subject:
        description: 建设主体
        type: string
      contract:
        description: 前期工作联系人
        type: string
      create_at:
        description: 创建时间
        type: string
      enter_db_type:
        description: 入库类别 0:A类,1:B类;2:C类
        type: integer
      id:
        description: id
        type: integer
      implement_type:
        description: 实施类型 0:新开工,1:续建
        type: integer
      investment_detail:
        description: 资金详情
        items:
          $ref: '#/definitions/vo.InvestmentDetail'
        type: array
      is_land_use:
        description: 是否有用地情况
        type: boolean
      level:
        description: 项目级别 0:区级,1:街镇级
        type: integer
      move_land_comsumption:
        description: 征迁/土地费用
        type: number
      name:
        description: 项目名称
        type: string
      need_collect:
        description: 需征地面积
        type: number
      need_people_move:
        description: 需拆迁农户/居民数(人)
        type: integer
      no_conform_use_plan:
        description: 不符合土地利用规划面积
        type: number
      period:
        description: 建设周期
        type: integer
      phone:
        description: 联系人手机号
        type: string
      plan_begin:
        description: 计划开工时间
        type: string
      point_type:
        description: 重点类型; 0:省重点实施项目,1:省重点预备项目,2:省重大产业项目;3:省4+1项目;4:省6千亿项目;5:市重点实施项目;6:市重点预备项目;7:无重点类型
        type: integer
      project_consumption:
        description: 工程费用
        type: number
      project_type:
        description: 项目类型; 0:安置房,1:道路交通,2:市政设施;3:提升整治;4:卫生;5:五水共治;6:学校;7:其他
        type: integer
      site_photo:
        description: 无拆迁照片
        type: string
      site_red:
        description: 选址红线 0:有拆迁,1:无拆迁
        type: integer
      status:
        description: 项目状态 0:草稿,1:已入库,2:前期计划;3:已发文"
        type: integer
      total:
        description: 总用亩
        type: number
      total_investment:
        description: 总投资
        type: number
      upload_cad_id:
        description: CAD文件ID(上传文件接口返回的ID)
        type: string
    type: object
  vo.ReserveUpdateReq:
    properties:
      add:
        description: 新增建设用地
        type: number
      company_business:
        description: 企/事业单位(家)
        type: integer
      construct_basis_necessity:
        description: 建设依据及必要性
        type: string
      construct_content_scope:
        description: 建设内容及规模
        type: string
      construct_site:
        description: 建设地点
        type: string
      construct_subject:
        description: 建设主体
        type: string
      contract:
        description: 前期工作联系人
        type: string
      enter_db_type:
        description: 入库类别 0:A类,1:B类;2:C类
        type: integer
      implement_type:
        description: 实施类型 0:新开工,1:续建
        type: integer
      investment_detail:
        description: |-
          资金详情 eg:
          "[{\\"type\\":0, \\"total\\":100, \\"detail\\":[{\\"total\\": 100,\\"year\\": \\"2022\\",\\"value\\":20,\\"comment\\":\\"xxx\\"}, {\\"total\\": 100,\\"year\\": \\"2023\\",\\"value\\":30,\\"comment\\":\\"xxx\\"}, ...]}, {}...]"
          type说明： 0:区财政;1:自筹;2:其他
        type: string
      is_land_use:
        description: 是否有用地情况
        type: boolean
      level:
        description: 项目级别 0:区级,1:街镇级
        type: integer
      move_land_comsumption:
        description: 征迁/土地费用
        type: number
      name:
        description: 项目名称
        type: string
      need_collect:
        description: 需征地面积
        type: number
      need_people_move:
        description: 需拆迁农户/居民数(人)
        type: integer
      no_conform_use_plan:
        description: 不符合土地利用规划面积
        type: number
      period:
        description: 建设周期
        type: integer
      phone:
        description: 联系人手机号
        type: string
      plan_begin:
        description: 计划开工时间
        type: string
      point_type:
        description: 重点类型; 0:省重点实施项目,1:省重点预备项目,2:省重大产业项目;3:省4+1项目;4:省6千亿项目;5:市重点实施项目;6:市重点预备项目;7:无重点类型
        type: integer
      project_consumption:
        description: 工程费用
        type: number
      project_type:
        description: 项目类型; 0:安置房,1:道路交通,2:市政设施;3:提升整治;4:卫生;5:五水共治;6:学校;7:其他
        type: integer
      site_photo:
        description: 无拆迁照片
        type: string
      site_red:
        description: 选址红线 0:有拆迁,1:无拆迁
        type: integer
      total:
        description: 总用亩
        type: number
      total_investment:
        description: 总投资
        type: number
      upload_cad_id:
        description: CAD文件ID(上传文件接口返回的ID)
        type: string
    type: object
info:
  contact:
    email: york-xia@gmail.com
    name: xiayoushuang
  description: 临安区政府投资项目管理后台API
  title: 临安区政府投资项目管理后台API
  version: "1.0"
paths:
  /api/v1/reserve/project:
    post:
      description: 创建储备库项目
      parameters:
      - description: ReserveReq
        in: body
        name: parameters
        required: true
        schema:
          $ref: '#/definitions/vo.ReserveReq'
      responses:
        "201":
          description: 创建储备库项目成功
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      security:
      - ApiKeyAuth: []
      summary: 创建储备库项目
      tags:
      - 储备库 - 项目
  /api/v1/reserve/project/{id}:
    delete:
      description: 删除储备库项目
      parameters:
      - description: 储备库项目id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: 删除储备库项目成功
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      security:
      - ApiKeyAuth: []
      summary: 删除储备库项目
      tags:
      - 储备库 - 项目
    get:
      description: 获取储备库项目
      parameters:
      - description: 储备库项目id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: 查询储备库项目成功
          schema:
            $ref: '#/definitions/vo.ReserveResp'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      security:
      - ApiKeyAuth: []
      summary: 获取储备库项目
      tags:
      - 储备库 - 项目
    put:
      description: 修改储备库项目
      parameters:
      - description: 储备库项目id
        in: path
        name: id
        required: true
        type: string
      - description: ReserveUpdateReq
        in: body
        name: parameters
        required: true
        schema:
          $ref: '#/definitions/vo.ReserveUpdateReq'
      responses:
        "200":
          description: 修改储备库项目成功
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      security:
      - ApiKeyAuth: []
      summary: 修改储备库项目
      tags:
      - 储备库 - 项目
  /api/v1/reserve/project/{id}/refer:
    patch:
      description: 提交储备库项目
      parameters:
      - description: 储备库项目id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: 提交储备库项目成功
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      security:
      - ApiKeyAuth: []
      summary: 提交储备库项目
      tags:
      - 储备库 - 项目
  /api/v1/reserve/project/{id}/submit:
    patch:
      description: 提报储备库项目
      parameters:
      - description: 储备库项目id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: 提报储备库项目成功
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      security:
      - ApiKeyAuth: []
      summary: 提报储备库项目
      tags:
      - 储备库 - 项目
  /api/v1/reserve/project/multi:
    delete:
      description: 批量删除储备库项目
      parameters:
      - description: 储备库项目id, `,` 连接
        in: query
        name: ids
        required: true
        type: string
      responses:
        "200":
          description: 批量删除储备库项目成功
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      security:
      - ApiKeyAuth: []
      summary: 批量删除储备库项目
      tags:
      - 储备库 - 项目
  /api/v1/reserve/project/submit/multi:
    patch:
      description: 批量提报储备库项目
      parameters:
      - description: 储备库项目id, `,` 连接
        in: query
        name: ids
        required: true
        type: string
      responses:
        "200":
          description: 批量提报储备库项目成功
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      security:
      - ApiKeyAuth: []
      summary: 批量提报储备库项目
      tags:
      - 储备库 - 项目
  /api/v1/reserve/projects:
    post:
      description: 获取储备库项目列表
      parameters:
      - description: 请求页
        in: query
        name: page
        type: integer
      - description: 页大小
        in: query
        name: page_size
        type: integer
      - description: ReserveFilterParam
        in: body
        name: parameters
        required: true
        schema:
          $ref: '#/definitions/vo.ReserveFilterParam'
      responses:
        "200":
          description: 查询储备库项目列表成功
          schema:
            allOf:
            - $ref: '#/definitions/vo.DataPagination'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/vo.ListReserveProResp'
                  type: array
              type: object
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      security:
      - ApiKeyAuth: []
      summary: 获取储备库项目列表
      tags:
      - 储备库 - 项目
  /auth/login:
    post:
      description: 用户登录
      parameters:
      - description: LoginReq
        in: body
        name: parameters
        required: true
        schema:
          $ref: '#/definitions/vo.LoginReq'
      responses:
        "200":
          description: 响应成功
          schema:
            $ref: '#/definitions/vo.LoginResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      summary: 用户登录
      tags:
      - 登录
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
