basePath: /
definitions:
  vo.Error:
    properties:
      args:
        items:
          type: string
        type: array
      code:
        type: integer
      msg:
        type: string
    type: object
  vo.LoginReq:
    properties:
      password:
        description: 密码
        type: string
      user_name:
        description: 用户名
        type: string
    type: object
  vo.LoginResponse:
    properties:
      access_token:
        description: token
        type: string
      expiry:
        description: token 到期时间 默认两小时
        type: integer
      token_type:
        description: 认证类型
        type: string
    type: object
info:
  contact:
    email: york-xia@gmail.com
    name: xiayoushuang
  description: 临安区政府投资项目管理后台API
  title: 临安区政府投资项目管理后台API
  version: "1.0"
paths:
  /auth/login:
    post:
      description: 用户登录
      parameters:
      - description: LoginReq
        in: body
        name: parameters
        required: true
        schema:
          $ref: '#/definitions/vo.LoginReq'
      responses:
        "200":
          description: 响应成功
          schema:
            $ref: '#/definitions/vo.LoginResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      summary: 用户登录
      tags:
      - 登录
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
